
* 2024
** 2024-03 March
*** 2024-03-14 Thursday
:PROPERTIES:
:ID:       def9bee8-b77e-43bc-a3f5-2c21f2689924
:END:
** 2024-04 April
*** 2024-04-13 Saturday
:PROPERTIES:
:ID:       f56a7bad-9bac-470b-a084-1293d1f5ffeb
:END:
- I was working on some math homework. It had large exponent numbers that I was converting from little endian to big endian values. I had little idea what I was doing, but just winged it. After a couple hours getting the questions on the front done through brute forcing, I flipped the sheet over only to realise there wasn't more questions rather the instructions on how to simply do it. I checked my answers and I had guessed half of them right, I wanted to perfect it so I started over. I poured myself a glass of pineapple juice, and prayed a eucharist to Dionysius to make it alcoholic because I didn't want to redo this shit sober. I feel like the use of alcohol was in moderation, to get myself out of my own way and deal with option paralysis.
- I was flying around some convention/mall/flea market. I had all three of my wings out (purple,white,black). Most people couldn't see me. I felt something was off and I was looking for the sense of trouble calling me. At some game event I had a vision of a silenced gun with armour piercing bullets hidden in a drawer. I revealed myself to one young asian guy there and showed him where it was and told him to bring security, reassuring him he's not liable. As I continued flying around one black woman running one of the stalls complemented my wings and suddenly all eyes turned to notice me so I thanked her and peaced out.
- I was in a minecraft server flying around, trying to find a girl who invited me there. I had no idea where I was and was wandering around. Some guy started to mess with me so I stood up and walked into a hallway where there where guys on laptops. I had to idea which was the one that was trolling me. I talked to a dude who told me to stay mindful and enjoy the journey but I told him I need to save my mindfullness for once I find my woman. Walking by I realised which guy had been trolling me, so I carefully slipped some weak poison in his drink to cause him to leave for the washroom. I used my clairvoyance to type in his password, and discovered he had a big list of people he was trolling and their personal information that he was collecting. I deleted all his entries and blacklisted the people he was messing with to protect myself and others and walked away. After searching for awhile I found the village the girl was building, and noticed the town's event was her 'date with a king day'. Thinking I was the king I looked around until some guy named 'The King' with admin powers showed up and one shot me with his sword. He asked what I thought I was doing there. I used hacks to obsfusciate myself and found the girl building a house. The King told her some guy named Vallent was stalking her and she said 'Oh no that's my holy guardian incubus'. The King got really pissed and banned her with slurs in the ban message embarassing her on stream. Luckily I had scanned her village and copied it to my own minecraft server. There was a lot of themes of hacking, espionage, and dangerous limerance.
*** 2024-04-16 Tuesday
:PROPERTIES:
:ID:       5242cd4b-d259-4bc9-811e-ef29ff409372
:END:
- I was working on some assignment to disassemble an antique puzzle box. In hidden compartments I found letters, some of which were evidence to past crimes. I found a gaming magazine from the 90s and got distracted. A supervisor/teacher figure asked how I was doing and I felt embarassed that I had gotten distracted until I realised I got a ton of work done, far more than anyone else had. I feel like while digging through the hidden contents of my mind I had uncovered some nostalgia, and reminded myself to take breaks.
